language: r
cache: packages

warnings_are_errors: FALSE

before_cache: Rscript -e 'remotes::install_cran("pkgdown")'

after_success:
  - Rscript -e 'pkgdown::build_site()'

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  keep-history: true
  local-dir: docs
  on:
    branch: master
